const PRODUCTS=[
{id:'crimson-ronin-tee',name:'Crimson Ronin Tee',category:'tees',price:39.99,tag:'LIMITED',desc:'A bold graphic tee built around the quiet strength of a wandering ronin.',fit:'Relaxed / oversized',fabric:'240gsm heavyweight cotton',drop:'The Origin / Limited',images:['assets/products/crimson-ronin-tee.jpg']},
{id:'silent-blade-tee',name:'Silent Blade Tee',category:'tees',price:39.99,tag:'ORIGIN',desc:'A monochrome streetwear essential inspired by precision, discipline and calm.',fit:'Oversized',fabric:'240gsm cotton jersey',drop:'The Origin / Limited',images:['assets/products/silent-blade-tee.jpg']},
{id:'rising-flame-tee',name:'Rising Flame Tee',category:'tees',price:39.99,tag:'NEW',desc:'A fiery graphic statement made for movement, confidence and late-night city energy.',fit:'Relaxed',fabric:'240gsm heavyweight cotton',drop:'The Origin / Limited',images:['assets/products/rising-flame-tee.jpg']},
{id:'storm-spirit-tee',name:'Storm Spirit Tee',category:'tees',price:39.99,tag:'DROP 01',desc:'A dark graphic silhouette inspired by pressure, power and the calm before the storm.',fit:'Oversized',fabric:'240gsm cotton jersey',drop:'The Origin / Limited',images:['assets/products/storm-spirit-tee.jpg']},
{id:'moonlit-warrior-tee',name:'Moonlit Warrior Tee',category:'tees',price:39.99,tag:'ORIGIN',desc:'A midnight-toned graphic tee inspired by solitary journeys and moonlit streets.',fit:'Relaxed',fabric:'240gsm heavyweight cotton',drop:'The Origin / Limited',images:['assets/products/moonlit-warrior-tee.jpg']},
{id:'shadow-ronin-tee',name:'Shadow Ronin Tee',category:'tees',price:39.99,tag:'LIMITED',desc:'A clean black tee with a cinematic ronin graphic for an understated street look.',fit:'Oversized',fabric:'240gsm cotton jersey',drop:'The Origin / Limited',images:['assets/products/shadow-ronin-tee.jpg']},
{id:'broken-oath-tee',name:'Broken Oath Tee',category:'tees',price:39.99,tag:'NEW',desc:'A dramatic graphic piece about resilience, freedom and choosing your own path.',fit:'Relaxed / oversized',fabric:'240gsm heavyweight cotton',drop:'The Origin / Limited',images:['assets/products/broken-oath-tee.jpg']},
{id:'midnight-ronin-hoodie',name:'Midnight Ronin Hoodie',category:'hoodies',price:64.99,tag:'LIMITED',desc:'A heavyweight everyday layer featuring a dark ronin graphic and oversized fit.',fit:'Oversized',fabric:'Heavyweight brushed fleece',drop:'The Origin / Limited',images:['assets/products/midnight-ronin-hoodie.jpg']},
{id:'stormborn-hoodie',name:'Stormborn Hoodie',category:'hoodies',price:69.99,tag:'DROP 01',desc:'A heavyweight hoodie inspired by storm energy, motion and controlled power.',fit:'Heavyweight oversized',fabric:'Brushed cotton fleece',drop:'The Origin / Limited',images:['assets/products/stormborn-hoodie.jpg']},
{id:'eternal-spirit-hoodie',name:'Eternal Spirit Hoodie',category:'hoodies',price:69.99,tag:'LIMITED',desc:'A statement heavyweight layer inspired by endurance, balance and an unbroken spirit.',fit:'Oversized',fabric:'Heavyweight brushed fleece',drop:'The Origin / Limited',images:['assets/products/eternal-spirit-hoodie.jpg']},
];
